* What's this about?
The intent of this text is to teach you general problem solving skills. We'll cover the following topics:
- Finding worthy problems
- Quickly evaluating problems
- Solving the problem
* The world is full of problems
The astute observer may have noticed that the world is full of problems, from large and almost intractable, to trivial. Even with seven billion people in this wonderful world, there are problems aplenty for everyone.

Our problems range from the global; war, poverty, needless death, limited resources, to the more simple; lawn mower needs fixing, math homework problems, automating backups of your computer.

Everyone has problems to solve. The more efficiently you can solve them, the better your life can be.
* So many problems, where should I start?
If you have a regular job, your boss may hand you problems. If you don't have a job, that's a problem to consider solving. If you have free time, maybe you can find some problems close by to solve. If you're retired, you can always make up problems called hobbies.
* Can I solve the problem?
Before you tackle a problem, you'll need to determine if it is within your ability to solve in a reasonable time. Depending on your situation, you may not know if you can solve the problem up front. Tackling problems that are just beyond your current abilities is a good way to grow, so don't be afraid of problems just because you don't currently have the tools or skill set to solve them. On the other hand, you may need to re-scope the problem or abandon it later if you find you are not making progress on the problem.
* Is the problem worth solving?
As you get practiced at finding problems, you may become overwhelmed by their number and variety. The guidance here would be to work on problems that interest you. Maybe this interest is driven externally; your boss needs his computer fixed or your partner would like the garden box built this weekend. Maybe your interest is driven internally; setting up that go-bag in case of emergency or finally setting up that solar charging station for your camping trip. Ultimately, it's up to you to determine whether a problem is worth solving.
* The problem solving loop
Now that you have selected your problem, you will need to start the process of solving it.

For trivial problems (defined as a problem that is easy to solve *for you*), the process may be very simple. 
