* What's this about?
The intent of this text is to teach you general problem solving skills. We'll cover the following topics:
- Finding worthy problems
- Quickly evaluating problems
- Solving the problem

* The world is full of problems
The world is a vast and complex place full of interesting problems, from large and almost intractable, to trivial. Even with seven billion people, there are problems aplenty for everyone. Our problems range from the global; war, poverty, needless death, limited resources, to the more simple; lawn mower needs fixing, math homework problems, automating backups of your computer. Everyone has problems to solve. The more efficiently you can solve them, the better your life can be.

* So many problems, where should I start?
Sometimes, problems find you. Sometimes you go searching for problems. Choosing the right problems to tackle will help you make more of an impact. The art of prioritizing problems is a topic unto itself. [[https://en.wikipedia.org/wiki/Maslow%27s_hierarchy_of_needs][Maslow's hierarchy of needs]] may be a good model to use when selecting problems to solve. Start at the bottom of the problem pyramid and work your way up. Stephen Covey's time management matrix is also a useful tool for selecting problems. See a simplified table below:

|               | urgent   | not urgent  |
|---------------+----------+-------------|
| important     | Do first | Do second   |
| not important | Do third | Do some day |

If you have a regular job, your boss may hand you problems. If you don't have a job, that's a problem to consider solving. If you have free time, maybe you can find some problems close by to solve. If you're retired, you can always make up problems called hobbies.

* Can I solve the problem?
Before you tackle a problem, you'll need to determine if it is within your ability to solve in a reasonable time. Depending on your situation, you may not know if you can solve the problem up front. Tackling problems that are just beyond your current abilities is a good way to grow, so don't be afraid of problems just because you don't currently have the tools or skill set to solve them. On the other hand, you may need to re-scope the problem or abandon it later if you find you are not making progress on the problem.

* Is the problem worth solving?
As you get practiced at finding problems, you may become overwhelmed by their number and variety. The guidance here would be to work on problems that interest you. Maybe this interest is driven externally; your boss needs his computer fixed or your partner would like the garden box built this weekend. Maybe your interest is driven internally; setting up that go-bag in case of emergency or finally setting up that solar charging station for your camping trip. Ultimately, it's up to you to determine whether a problem is worth solving.

* The problem solving loop
Now that you have selected your problem, you will need to start the process of solving it. The summary of the process is:
1. Gather data to understand the problem.
2. Gather options to solve the problem.
3. Choose your solution.
4. Implement your solution.
5. Evaluate the effectiveness of the solution (Stop here if you consider the problem solved)
6. Is it still worthwhile pursuing this problem? If so, repeat from step 1.

For trivial problems (defined as a problem that is easy to solve *for you*), the process may be very simple. 

